# Generated by Django 5.0.4 on 2024-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='button/icons/')),
                ('name', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField()),
                ('tap_step', models.PositiveSmallIntegerField()),
                ('bonus', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'button',
                'verbose_name_plural': 'buttons',
                'db_table': 'buttons',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='channels/avatar/')),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('bonus', models.PositiveIntegerField()),
                ('expires_at', models.DateField()),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'db_table': 'channels',
            },
        ),
    ]
