# Generated by Django 5.0.4 on 2024-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
