# Generated by Django 5.0.4 on 2024-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_button_description_button_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
