# Generated by Django 5.0.4 on 2024-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_button_name'),
        ('user', '0003_alter_user_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='seconds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='buttons', to='user.user'),
        ),
    ]
