# Generated by Django 5.0.4 on 2024-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refered_by',
            field=models.ManyToManyField(related_name='friends', to='user.user'),
        ),
    ]
